## NUMPY BASICS

### CREATING A NUMPY ARRAY

In [ ]:
import numpy as np

list_a = [2,5,8,9]

#Changing a list into array
##Creating a 1D array
one_d_numpy_array = np.array(list_a)

print(one_d_numpy_array)
print("Dimensions: ",one_d_numpy_array.ndim)

[2 5 8 9]
Dimensions:  1


In [ ]:
##Making a zero dimensional array
zero_d_array = np.array(1)
print(zero_d_array)

print("Dimension: ",zero_d_array.ndim)

1
Dimension:  0


In [ ]:
##2D array

two_d = [[1,2,3], [4,5,6]] ##Creating a list
two_d_array = np.array(two_d) #Converting a list into numpy array
print(two_d_array) #Printing the array
print("Dimensions: ", two_d_array.ndim) #Printing dimensions of the array
print("Shape of the array: ", two_d_array.shape) #Printing the shape of the array (row, column)
print("Size of the array: ", two_d_array.size) #Printing the size of the array (row x columns - number of elements)
print("Datatype of array: ", two_d_array.dtype) #Printng the datatype of elements present in the array

[[1 2 3]
 [4 5 6]]
Dimensions:  2
Shape of the array:  (2, 3)
Size of the array:  6
Datatype of array:  int64


### Indexing in numpy array

In [ ]:
arr = np.array([3,5,7,9,11])
print(arr[0]) ##getting the first element of the array using index

print(arr[3] + arr[4])

3
20


In [ ]:
arr_2d = np.array([[1,2,3, 4],[6,7,8,9]])
print(arr_2d)
print("Accessing the 2nd row and then the third col element: ",arr_2d[1,2])

print("Accessing the 2nd row and then the second col element: ",arr_2d[1,1])

[[1 2 3 4]
 [6 7 8 9]]
Accessing the 2nd row and then the third col element:  8
Accessing the 2nd row and then the second col element:  7


In [ ]:
arr_3d = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]], #0th height (z dimension)
                   [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]]) #1st height (z dimension)
print(arr_3d)
print(arr_3d[0,2]) ##0th height and 3rd row
print(arr_3d[0,2,2]) ##0th height and 3rd row and third col

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]
[7 8 9]
9


In [ ]:
arr_3d = np.array([[[1,2,3],[3,2,1]], #0th height (z dimension)
                   [[4,5,6],[7,8,9]]]) #1st height (z dimension)
print(arr_3d)
print(arr_3d[1,1,1]) ##0th height and 3rd row
# print(arr_3d[0,2,2]) ##0th height and 3rd row and third col

[[[1 2 3]
  [3 2 1]]

 [[4 5 6]
  [7 8 9]]]
8


In [ ]:
arr_3d_neg = np.array([[[1,2,3],[3,2,1]], #0th height (z dimension)
                   [[4,5,6],[7,8,9]]]) #1st height (z dimension)
print(arr_3d_neg)
print(arr_3d_neg[1,-2,-1])

[[[1 2 3]
  [3 2 1]]

 [[4 5 6]
  [7 8 9]]]
6


## SLICING IN NUMPY ARRAY

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[1:5]) #second index to 5th index
print(arr[3:-2])

print(arr[1:6:2]) #Starts from 2nd and skips every2 steps
##[start:end]
##[start:end:step]

[2 3 4 5]
[4 5 6 7]
[2 4 6]


In [ ]:
arr_2d = np.array([[1,2,3, 4],[6,7,8,9],[9,10,11,12]])
print(arr_2d)

print(arr_2d[0:1])
print('----')
print(arr_2d[1:2,0:2])
print(arr_2d[1,0:2])

[[ 1  2  3  4]
 [ 6  7  8  9]
 [ 9 10 11 12]]
[[1 2 3 4]]
----
[[6 7]]
[6 7]


In [ ]:
arr_2d_2 = np.array([[2,4,6,8,11],[1,3,5,7,9]])
print(arr_2d_2[0,1:-2])

[4 6]


## Class work

In [ ]:
#1. numpy array from list [7, 14, 21, 28]

list_1 = [7, 14, 21, 28]

array_1 = np.array(list_1)
print(array_1)

[ 7 14 21 28]


In [ ]:
#2.numpy array [[5,10,15],[20,25,30]], print shape and dims

list_2 = [[5,10,15],[20,25,30]]

array_2 = np.array(list_2)
print(array_2)
print(array_2.shape)
print(array_2.ndim)

[[ 5 10 15]
 [20 25 30]]
(2, 3)
2


In [ ]:
#3. np.zeroes for 2d array of shape (2,3), use np.arange tp create array from 1,12 with step of 3

zeroes_array = np.zeros([2,3])

print(zeroes_array)

array_3 = np.arange(0,12,3)
print(array_3)

[[0. 0. 0.]
 [0. 0. 0.]]
[0 3 6 9]


In [ ]:
#4. array = [2,4,6,8] and multiply by 3

list_4 = [2,4,6,8]

array_4 = np.array(list_4)
print("Original array:", array_4)
array_4_2 = array_4 * 3
print("Multiplied by 3:",array_4_2)

Original array: [2 4 6 8]
Multiplied by 3: [ 6 12 18 24]


In [ ]:
#5 array = [1,3,5,7,9,11] - third element and 1:3 slice
list_5 = [1,3,5,7,9,11]
array_5 = np.array(list_5)
print("Third element:", array_5[2])
print("Elemnets from 1 to 3:",array_5[1:4])

Third element: 5
Elemnets from 1 to 3: [3 5 7]


In [ ]:
arr6 = np.array([1,3,5,7,9,11])
print(arr6)

[ 1  3  5  7  9 11]


In [1]:
_name = "hello"

In [2]:
_name

'hello'