##Hands on practice : Linear Algebra for AI

###Exercise 1 :Working with Scalars and Vectors

In [ ]:
import numpy as np
#creating a scalar
scalar = 7
#creating a vector
vector = np.array([3,5,7])
print("Vector:",vector)

#Scaling vector through a scalar aka scaled vector
scaled_vector = scalar * vector
print('Scaled vector : ',scaled_vector)

Vector: [3 5 7]
Scaled vector :  [21 35 49]


Exercise 2 addition and subtraction

In [ ]:
import numpy as np
vector1 = np.array([3,6,9])
vector2 = np.array([3,4,5])
res = vector1 + vector2
result = vector1 - vector2
print("The addition res is :",res)
print("The subtraction result is : ", result)

The addition res is : [ 6 10 14]
The subtraction result is :  [0 2 4]


Exercise 3:Matrix Creation and Basic Operation

In [ ]:
import numpy as np
matrix1 = np.array([[2,4],[5,7]])
matrix2 = np.array([[6,8],[9,11]])
add = matrix1 + matrix2
print("The addition result is:",add)
print("The sub is ", matrix1 - matrix2)
print("The matrix is :", matrix1)

The addition result is: [[ 8 12]
 [14 18]]
The matrix is : [[2 4]
 [5 7]]


In [ ]:
import numpy as np
matrix1 = np.array([[1,2,3],[1,1,1],[4,4,4]])
matrix2 = np.array([[1,5,2],[4,2,3],[1,1,3]])
res = np.dot(matrix1,matrix2)
print(res)

[[12 12 17]
 [ 6  8  8]
 [24 32 32]]


In [ ]:
import numpy as np
mat1 = np.array([[1,3],[9,3]])
result = np.dot(mat1,mat1)
print(result)

[[28 12]
 [36 36]]


In [ ]:
m1 = np.array([[2,4],[5,7]])
m2 = np.array([[2,3],[2,2]])
a = (m1[0,0] * m2[0,0])+(m1[0,1] * m2[1,0])
b = (m1[0,0]* m2[0,1])+(m1[0,1]*m2[1,1])
c = (m1[1,0]*m2[0,0]) + (m1[1,1]*m2[1,0])
d = (m1[1,0]*m2[0,1])+ (m1[1,1]*m2[1,1])
print(a)
print(b)
print(c)
print(d)
result = np.dot(m1,m2)
print("The dot product is : ",result)

12
14
24
29
The dot product is :  [[12 14]
 [24 29]]


Exercise 5: Identity matrix and transpose

In [ ]:
import numpy as np
identity = np.eye(2)
print(identity)
# transpose
m1 = np.array([[2,4],[5,7]])
transpose = m1.T
print(transpose)

print(m1)

a = m1[0,0] , m1[1,0]
# b = m1[1,0]
c = m1[0,1] , m1[1,1]
# d = m1[1,1]
print(a)

print(c)


[[1. 0.]
 [0. 1.]]
[[2 5]
 [4 7]]
[[2 4]
 [5 7]]
(np.int64(2), np.int64(5))
(np.int64(4), np.int64(7))


In [ ]:
matrix1=np.array([[2,4],[5,7]])

print(np.linalg.inv(matrix1))
inverse=np.linalg.inv(matrix1)
mat_inv=np.dot(matrix1,inverse)
print(mat_inv)

[[-1.16666667  0.66666667]
 [ 0.83333333 -0.33333333]]
[[1.0000000e+00 0.0000000e+00]
 [4.4408921e-16 1.0000000e+00]]
